name: veton
proxy:
  nodeservice:
    - veton.lndo.site:3000
  phpservice:
    - api.lndo.site
services:
  nodeservice:
    type: node:10
    build:
      - "npm install pm2 -g"
      - "cd /app/front && npm install"
    port: 3000
  phpservice:
    type: php:7.2
    webroot: back/public
    via: apache:2.4
    build:
      - "cd /app/back && composer install"
  dbservice:
    type: mariadb:10.2.21
    portfoward: true
    creds:
      user: mariadb
      password: mariadb
      database: veton
tooling:
  node:
    service: nodeservice
  npm:
    service: nodeservice
    cmd:
      - "npm"
      - "--cwd=/app/front"
  pm2:
    service: nodeservice
    cmd:
      - "pm2"
events:
  post-start:
    - nodeservice: "cd /app/front && npm install && cd /app && pm2 start ecosystem.yml"