<?php

use Illuminate\Database\Seeder;

class PetsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('pets')->insert([
            'id_pet' => 1,
            'id_user' =>2,
            'id_type' =>1,
            'id_breed' =>1,
            'id_gender' =>1,
            'name' => 'Luli',
            'last_name' =>'Pérez',
            'birthday'=>'2010-08-20 13:45:12',
            'image'=>'luli.jpg',
            'weight'=>7,
            'colors' =>'Blanca y negra',
            'comments'=> 'Es una gata amorosa.',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s'),
        ]);
        DB::table('pets')->insert([
            'id_pet' => 2,
            'id_user' =>3,
            'id_type' =>2,
            'id_breed' =>1,
            'id_gender' =>2,
            'name' => 'Chocolate',
            'last_name' =>'Fernández',
            'birthday'=>'2012-06-20 13:45:12',
            'image'=>'chocolate.jpg',
            'weight'=>14,
            'colors' =>'Marrón oscuro',
            'comments'=> 'Un integrante más de la familia',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s'),
        ]);
        DB::table('pets')->insert([
            'id_pet' => 3,
            'id_user' =>3,
            'id_type' =>2,
            'id_breed' =>1,
            'id_gender' =>2,
            'name' => 'Aldo',
            'last_name' =>'Fernández',
            'birthday'=>'2012-06-20 13:45:12',
            'image'=>'aldo.jpg',
            'weight'=>12,
            'colors' =>'Negro',
            'comments'=> 'Perro guardian, tamaño medio, se lleva bien con otros animales.',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s'),
        ]);
        DB::table('pets')->insert([
            'id_pet' => 4,
            'id_user' =>10,
            'id_type' =>1,
            'id_breed' =>45,
            'id_gender' =>2,
            'name' => 'Bills',
            'last_name' =>'Diaz',
            'birthday'=>'2012-06-20 13:45:12',
            'image'=>'bills.jpg',
            'weight'=>3,
            'colors' =>'Rosa',
            'comments'=> 'Nombre inspirado en dragon ball super.Es el dios de la destrucción, quien mantiene el equilibrio en el universo. Es el ser mas poderoso. Este nombre describe bien a mi gato :P',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s'),
        ]);
        DB::table('pets')->insert([
            'id_pet' => 5,
            'id_user' =>10,
            'id_type' =>2,
            'id_breed' =>4,
            'id_gender' =>1,
            'name' => 'Azul',
            'last_name' =>'Diaz',
            'birthday'=>'2012-06-20 13:45:12',
            'image'=>'azul.jpg',
            'weight'=>15,
            'colors' =>'Negra',
            'comments'=> 'Es una perra muy tranquila, rescatada de la calle. Se lleva muy bien con otros animales, perros y gatos.',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s'),
        ]);
        DB::table('pets')->insert([
            'id_pet' => 6,
            'id_user' =>11,
            'id_type' =>2,
            'id_breed' =>4,
            'id_gender' =>2,
            'name' => 'Braulio',
            'last_name' =>'Nieto',
            'birthday'=>'2012-06-20 13:45:12',
            'image'=>'braulio.jpg',
            'weight'=>9,
            'colors' =>'blanco',
            'comments'=> 'Braulio es un perro mestizo rescatado de la calle. Es de tamaño mediano pero se siente un gigante. Es muy amigable con sus dueños y conocidos, no lo es tanto con los desconocidos, pero es inofensivo',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s'),
        ]);
        DB::table('pets')->insert([
            'id_pet' => 7,
            'id_user' =>11,
            'id_type' =>2,
            'id_breed' =>7,
            'id_gender' =>2,
            'name' => 'Chad',
            'last_name' =>'Nieto',
            'birthday'=>'2012-06-20 13:45:12',
            'image'=>'chad.jpg',
            'weight'=>12,
            'colors' =>'Amarillo',
            'comments'=> 'Chad es un perro muy inteligente, obediente y amigable.',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s'),
        ]);
        DB::table('pets')->insert([
            'id_pet' => 8,
            'id_user' =>2,
            'id_type' =>1,
            'id_breed' =>43,
            'id_gender' =>2,
            'name' => 'Tom',
            'last_name' =>'Pérez',
            'birthday'=>'2015-02-20 13:45:12',
            'image'=>'tom.jpg',
            'weight'=>5,
            'colors' =>'Gris',
            'comments'=> 'Es un cazador nato.',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s'),
        ]);
        DB::table('pets')->insert([
            'id_pet' => 9,
            'id_user' =>2,
            'id_type' =>1,
            'id_breed' =>41,
            'id_gender' =>1,
            'name' => 'Fiaca',
            'last_name' =>'Pérez',
            'birthday'=>'2014-03-18 13:45:12',
            'image'=>'fiaca.jpg',
            'weight'=>7,
            'colors' =>'Anaranjada',
            'comments'=> 'Hace honor a su nombre, está todo el día haciendo fiaca.',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s'),
        ]);
        DB::table('pets')->insert([
            'id_pet' => 10,
            'id_user' =>2,
            'id_type' =>1,
            'id_breed' =>44,
            'id_gender' =>2,
            'name' => 'Puma',
            'last_name' =>'Pérez',
            'birthday'=>'2012-04-15 13:45:12',
            'image'=>'puma.jpg',
            'weight'=>6,
            'colors' =>'Marrón Claro',
            'comments'=> 'Es muy guardián del hogar.',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s'),
        ]);
        DB::table('pets')->insert([
            'id_pet' => 11,
            'id_user' =>3,
            'id_type' =>2,
            'id_breed' =>28,
            'id_gender' =>2,
            'name' => 'Gigante',
            'last_name' =>'Fernández',
            'birthday'=>'2010-05-15 13:45:12',
            'image'=>'gigante.jpg',
            'weight'=>3,
            'colors' =>'Blanco',
            'comments'=> 'Es muy activo, no para un segundo.',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s'),
        ]);
        DB::table('pets')->insert([
            'id_pet' => 12,
            'id_user' =>3,
            'id_type' =>2,
            'id_breed' =>35,
            'id_gender' =>2,
            'name' => 'Chino',
            'last_name' =>'Fernández',
            'birthday'=>'2008-06-10 13:45:12',
            'image'=>'chino.jpg',
            'weight'=>5,
            'colors' =>'Marrón',
            'comments'=> 'Cabrón, se enoja por todo.',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s'),
        ]);
        DB::table('pets')->insert([
            'id_pet' => 13,
            'id_user' =>3,
            'id_type' =>2,
            'id_breed' =>27,
            'id_gender' =>2,
            'name' => 'Pirata',
            'last_name' =>'Fernández',
            'birthday'=>'2010-04-11 13:45:12',
            'image'=>'pirata.jpg',
            'weight'=>15,
            'colors' =>'Negro y Blanco',
            'comments'=> 'Extremadamente inteligente.',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s'),
        ]);
        DB::table('pets')->insert([
            'id_pet' => 14,
            'id_user' =>10,
            'id_type' =>1,
            'id_breed' =>42,
            'id_gender' =>2,
            'name' => 'Manchita',
            'last_name' =>'Diaz',
            'birthday'=>'2012-05-15 13:45:12',
            'image'=>'manchita.jpg',
            'weight'=>8,
            'colors' =>'Naranja y Blanco',
            'comments'=> 'Es un gato muy activo.',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s'),
        ]);
        DB::table('pets')->insert([
            'id_pet' => 15,
            'id_user' =>10,
            'id_type' =>2,
            'id_breed' =>30,
            'id_gender' =>2,
            'name' => 'Rudo',
            'last_name' =>'Diaz',
            'birthday'=>'2014-07-10 13:45:12',
            'image'=>'rudo.jpg',
            'weight'=>18,
            'colors' =>'Blanco',
            'comments'=> 'Es tranquilo, pero se pone furioso cuando ve a otro perro.',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s'),
        ]);
        DB::table('pets')->insert([
            'id_pet' => 16,
            'id_user' =>11,
            'id_type' =>1,
            'id_breed' =>38,
            'id_gender' =>1,
            'name' => 'Lady',
            'last_name' =>'Nieto',
            'birthday'=>'2012-08-20 13:45:12',
            'image'=>'lady.jpg',
            'weight'=>7,
            'colors' =>'Blanco',
            'comments'=> 'Elegancia felina.',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s'),
        ]);
        DB::table('pets')->insert([
            'id_pet' => 17,
            'id_user' =>11,
            'id_type' =>1,
            'id_breed' =>39,
            'id_gender' =>1,
            'name' => 'Peluda',
            'last_name' =>'Nieto',
            'birthday'=>'2011-09-21 13:45:12',
            'image'=>'peluda.jpg',
            'weight'=>8,
            'colors' =>'Gris con Negro',
            'comments'=> 'Es una gata muy cariñosa y tranquila.',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s'),
        ]);
        DB::table('pets')->insert([
            'id_pet' => 18,
            'id_user' =>12,
            'id_type' =>2,
            'id_breed' =>5,
            'id_gender' =>2,
            'name' => 'Narciso',
            'last_name' =>'Salazar',
            'birthday'=>'2012-08-18 13:45:12',
            'image'=>'narciso.jpg',
            'weight'=>18,
            'colors' =>'Negro',
            'comments'=> 'Es un gran compañero.',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s'),
        ]);
        DB::table('pets')->insert([
            'id_pet' => 19,
            'id_user' =>12,
            'id_type' =>2,
            'id_breed' =>6,
            'id_gender' =>2,
            'name' => 'Octavio',
            'last_name' =>'Salazar',
            'birthday'=>'2013-09-19 13:45:12',
            'image'=>'octavio.jpg',
            'weight'=>15,
            'colors' =>'Marrón y Negro',
            'comments'=> 'Es una masa.',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s'),
        ]);
        DB::table('pets')->insert([
            'id_pet' => 20,
            'id_user' =>12,
            'id_type' =>2,
            'id_breed' =>9,
            'id_gender' =>2,
            'name' => 'Anastasio',
            'last_name' =>'Salazar',
            'birthday'=>'2016-10-19 13:45:12',
            'image'=>'anastasio.jpg',
            'weight'=>8,
            'colors' =>'Blanco, Marrón y Negro',
            'comments'=> 'Es muy activo.',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s'),
        ]);
        DB::table('pets')->insert([
            'id_pet' => 21,
            'id_user' =>12,
            'id_type' =>2,
            'id_breed' =>14,
            'id_gender' =>2,
            'name' => 'Anacleto',
            'last_name' =>'Salazar',
            'birthday'=>'2018-11-15 13:45:12',
            'image'=>'anacleto.jpg',
            'weight'=>14,
            'colors' =>'Marrón y Blanco',
            'comments'=> 'Es amigable y cariñoso.',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s'),
        ]);
    }
}
